[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "truefy-backend"
version = "1.0.0"
description = "Deepfake detection backend"
requires-python = ">=3.9,<3.10"

